# Generated by Django 2.2.12 on 2020-05-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200530_0557"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="gggfgf",),
        migrations.RemoveField(model_name="customtext", name="jhgj",),
        migrations.RemoveField(model_name="customtext", name="jhgjh",),
        migrations.RemoveField(model_name="customtext", name="kjuyiu",),
        migrations.RemoveField(model_name="customtext", name="nbhjg",),
        migrations.RemoveField(model_name="customtext", name="uyiuyi",),
    ]
